const actionTypes = {
  FETCH_TAREAS_SUCCESS: 'FETCH_TAREAS_SUCCESS',
  FETCH_IMAGES_SUCCESS: 'FETCH_IMAGES_SUCCESS',
  QUERY_TAREA_RESULT: 'QUERY_TAREA_RESULT',
  CLEAN_RESULT_QUERY: 'CLEAN_RESULT_QUERY'
};

export default actionTypes;