const actionTypes = {
  FETCH_TAREAS: 'FETCH_TAREAS',
  FETCH_IMAGES_TAREA: 'FETCH_IMAGES_TAREA',
  QUERY_TAREA_RESULT: 'QUERY_TAREA_RESULT',
  CLEAN_RESULT_QUERY: 'CLEAN_RESULT_QUERY'
};

export default actionTypes;